# Generated by Django 5.2.8 on 2026-08-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, default='', max_length=100)),
                ('mother_name', models.CharField(blank=True, default='', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('blood_group', models.CharField(blank=True, default='O+', max_length=10)),
                ('category', models.CharField(default='General', max_length=20)),
                ('aadhaar_number', models.CharField(blank=True, default='', max_length=20)),
                ('student_phone', models.CharField(blank=True, default='', max_length=20)),
                ('parent_phone', models.CharField(blank=True, default='', max_length=20)),
                ('permanent_address', models.TextField(blank=True, default='')),
                ('current_address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', max_length=30)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('previous_school_college', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Verified', 'Verified')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sif', to='students.studentprofile')),
            ],
        ),
    ]
