# Generated by Django 5.2.8 on 2026-08-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_subject'),
        ('faculty', '0002_facultyleave'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(default='09:00 AM - 10:00 AM', max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('approval_status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending Approval', max_length=30)),
                ('admin_remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.classroom')),
                ('original_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_requests', to='faculty.facultyprofile')),
                ('proxy_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_proxies', to='faculty.facultyprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.subject')),
            ],
        ),
    ]
